---
- name: Aplicar Schedule com RRULESET (Dias Úteis) em múltiplos Job Templates
  hosts: localhost
  gather_facts: false

  vars:
    lista_de_jobs:
       - PKGS
    hora_execucao: "09:00:00"  # horário fixo
    timezone: "America/Sao_Paulo"


  tasks:
    - name: Gerar DTSTART no formato UTC com hora 09:00
      shell: date -u +%Y%m%dT090000Z
      register: dtstart_cmd

    - name: Definir dtstart_formatado
      set_fact:
        dtstart_formatado: "{{ dtstart_cmd.stdout }}"

    - name: Definir RRULE completa
      set_fact:
        rrule_final: >-
          DTSTART:{{ dtstart_formatado }}
          RRULE:FREQ=DAILY;INTERVAL=1;BYDAY=MO,TU,WE,TH,FR

    - name: Aplicar schedule em cada Job Template
      loop: "{{ lista_de_jobs }}"
      loop_control:
        loop_var: job_template_nome
      ansible.controller.schedule:
        name: "agendamento-diautil-{{ job_template_nome }}"
        state: present
        unified_job_template: "{{ job_template_nome }}"
        rrule: "{{ rrule_final | regex_replace('\n', '') }}"
        enabled: true
        extra_data:
          origem: schedule_dia_util
