---
- name: Simular consulta a API de dados financeiros com ODATE e CALCDATE
  hosts: aap01.aroque.com.br
  gather_facts: false

  vars:
    ODATE: "{{ lookup('pipe', 'date +%Y-%m-%d') }}"  # Pode ser sobrescrito via survey ou workflow
    CALCDATE: "{{ lookup('pipe', 'date -d \"+1 day\" +%Y-%m-%d') }}"
    api_url: "http://192.168.100.11:8182/dados_financeiros.csv"
    dados_originais: "/home/ansible/dados_financeiros.csv"
    dados_filtrados: "/home/ansible/resultado_api_{{ ODATE }}.csv"

  tasks:
    - name: Exibir ODATE e CALCDATE
      debug:
        msg: "ODATE: {{ ODATE }} | CALCDATE: {{ CALCDATE }}"

    - name: Baixar CSV simulado da API
      get_url:
        url: "{{ api_url }}"
        dest: "{{ dados_originais }}"
        mode: '0644'
        force: true
      register: resultado_download
      failed_when: resultado_download.failed

    - name: Filtrar transações para a data ODATE
      shell: |
        head -n1 {{ dados_originais }} > {{ dados_filtrados }}
        grep {{ ODATE }} {{ dados_originais }} >> {{ dados_filtrados }}
      args:
        executable: /bin/bash

    - name: Exibir conteúdo do CSV filtrado
      shell: cat {{ dados_filtrados }}
      register: conteudo_csv

    - name: Mostrar resultado
      debug:
        var: conteudo_csv.stdout

    - name: Publicar variáveis para o fluxo
      set_stats:
        data:
          caminho_do_arquivo: "{{ dados_filtrados }}"
          odate_utilizada: "{{ ODATE }}"
          data_processamento: "{{ CALCDATE }}"