---
- name: Transferir arquivo de um host remoto para outro
  hosts: localhost
  gather_facts: false

  vars:
    src_host: "{{ host_origem }}"
    dest_host: "{{ host_destino }}"
    caminho_do_arquivo: "{{ caminho_do_arquivo }}"
    caminho_destino: "{{ caminho_destino }}"
    nome_arquivo: "{{ caminho_do_arquivo | basename }}"
    arquivo_local: "/tmp/{{ nome_arquivo }}"

  tasks:
    - name: Buscar arquivo do host de origem
      ansible.builtin.fetch:
        src: "{{ caminho_do_arquivo }}"
        dest: "{{ arquivo_local }}"
        flat: true
      delegate_to: "{{ src_host }}"
      run_once: true

    - name: Enviar arquivo para o host de destino
      ansible.builtin.copy:
        src: "{{ arquivo_local }}"
        dest: "{{ caminho_destino }}/{{ nome_arquivo }}"
      delegate_to: "{{ dest_host }}"
      run_once: true

    - name: Publicar caminho final do arquivo
      set_stats:
        data:
          arquivo_enviado_para: "{{ dest_host }}:{{ caminho_destino }}/{{ nome_arquivo }}"
