---
- name: Transferir arquivo entre servidores sem rsync, com fallback de nome
  hosts: localhost
  gather_facts: false

  vars:
    src_host: "{{ host_origem }}"
    dest_host: "{{ host_destino }}"
    caminho_do_arquivo: "{{ caminho_do_arquivo }}"
    caminho_destino: "{{ caminho_destino }}"

  tasks:
    - name: Buscar arquivo do host de origem
      ansible.builtin.fetch:
        src: "{{ caminho_csv }}"
        dest: "{{ arquivo_local }}"
        flat: true
      delegate_to: "{{ src_host }}"
      run_once: true

    - name: Copiar arquivo para o host de destino
      ansible.builtin.copy:
        src: "{{ caminho_do_arquivo }}"
        dest: "{{ caminho_destino }}"A
      delegate_to: "{{ dest_host }}"
      run_once: true

    - name: Publicar variável com o destino final
      set_stats:
        data:
          arquivo_enviado_para: "{{ dest_host }}:{{ caminho_destino }}"

    - name: Confirmar envio
      debug:
        msg: "Arquivo transferido para {{ arquivo_enviado_para }}"
