---
- name: Transferir arquivo para servidor remoto
  hosts: aap01.aroque.com.br
  gather_facts: false

  vars:
    caminho_csv: "{{ caminho_csv }}"
    servidor_destino: "{{ servidor_destino }}"
    caminho_destino: "{{ caminho_destino }}"

  tasks:
    - name: Verificar se o arquivo existe
      stat:
        path: "{{ caminho_csv }}"
      register: arquivo_stat

    - name: Falhar se o arquivo não existir
      fail:
        msg: "Arquivo {{ caminho_csv }} não encontrado."
      when: not arquivo_stat.stat.exists

    - name: Enviar arquivo para servidor remoto
      ansible.posix.synchronize:
        src: "{{ caminho_csv }}"
        dest: "{{ caminho_destino }}/"
        mode: push
      delegate_to: "{{ servidor_destino }}"

    - name: Publicar destino do arquivo
      set_stats:
        data:
          arquivo_enviado_para: "{{ servidor_destino }}:{{ caminho_destino }}/"

    - name: Confirmar envio
      debug:
        msg: "Arquivo transferido para {{ arquivo_enviado_para }}"
