---
- name: Copiar arquivo diretamente de um servidor remoto para outro
  hosts: "{{ host_node }}"
  gather_facts: false
  become: false

  vars:
    src_host: ""        # Nome do host de origem (definido no inventário)
    src_path: ""        # Caminho completo no host de origem
    dest_path: ""       # Caminho completo no host de destino

  tasks:
    - name: Copiar arquivo do host de origem diretamente para este host
      ansible.posix.synchronize:
        src: "{{ src_path }}"
        dest: "{{ dest_path }}"
        mode: pull
      delegate_to: "{{ src_host }}"