---
- name: Validar se hoje é o 1º dia útil do mês
  hosts: localhost
  gather_facts: false

  vars:
    calendario_url: "http://192.168.100.11:8181/dias_uteis.csv"
    calendario_local: "/tmp/dias_uteis.csv"
    hoje: "{{ lookup('pipe', 'date +%Y-%m-%d') }}"
    
  tasks:
    - name: Format DTSTART e RRULE
      set_fact:
        dtstart_formatado: "{{ lookup('pipe', 'date +%Y%m%dT090000') }}"
        rrule_final: >-
          DTSTART;TZID={{ timezone }}:{{ dtstart_formatado }}
          RRULE:FREQ=DAILY;INTERVAL=1;BYDAY=MO,TU,WE,TH,FR

    - name: Aplicar schedule para cada Job Template
      loop: "{{ lista_de_jobs }}"
      loop_control:
        loop_var: job_template_nome
      ansible.controller.schedule:
        name: "agendamento-diautil-{{ job_template_nome }}"
        state: present
        unified_job_template: "{{ job_template_nome }}"
        rrule: "{{ rrule_final | regex_replace('\n', '') }}"
        enabled: true
        extra_data:
          origem: schedule_dia_util