---
- name: Gerenciar serviço no host
  hosts: all
  gather_facts: false
  vars:
    service_name: ""
    service_state: "started"  # started | stopped | restarted
    enabled: true
  tasks:
    - name: Alterar estado do serviço
      ansible.builtin.systemd:
        name: "{{ service_name }}"
        state: "{{ service_state }}"
        enabled: "{{ enabled }}"