---
- name: Validar se hoje é dia útil segundo calendário remoto (B3)
  hosts: aap01.aroque.com.br
  gather_facts: false

  vars:
    calendario_url: "http://192.168.100.11:8181/b3_2025.csv"  # pode ser sobrescrito via extra_vars
    calendario_local: "/tmp/b3_2025.csv"

  tasks:
    - name: Obter data atual
      set_fact:
        data_hoje: "{{ lookup('pipe', 'date +%Y-%m-%d') }}"

    - name: Baixar calendário do servidor remoto
      get_url:
        url: "{{ calendario_url }}"
        dest: "{{ calendario_local }}"
        mode: '0444'
        force: true
      register: resultado_download
      failed_when: resultado_download.failed

    - name: Verificar se a data atual está no calendário de feriados
      shell: grep -Fxq {{ data_hoje }} {{ calendario_local }}
      register: resultado_calendario
      ignore_errors: true

    - name: Definir variável execucao_permitida (true se NÃO for feriado)
      set_stats:
        data:
          execucao_permitida: "{{ resultado_calendario.rc != 0 }}"

    - name: Exibir status da execução
      debug:
        msg: >-
          Execução {{ 'permitida' if resultado_calendario.rc != 0 else 'bloqueada' }} para {{ data_hoje }}

    - name: Falhar se a data não for permitida
      fail:
        msg: "Execução bloqueada para {{ data_hoje }} — data consta como feriado no calendário B3."
      when: resultado_calendario.rc == 0

    - name: Exibir status da execução
      debug:
        msg: "Execução permitida para {{ data_hoje }}"
      when: resultado_calendario.rc != 0